[package]
name = "atomic_pingpong"
version = "0.1.0"
edition = "2021"
authors = ["David Lawrence <dlaw@dlaw.me>"]
license = "MIT"
repository = "https://github.com/dlaw/atomic_pingpong/"
description = "Lightweight ping-pong buffer using AtomicU8 for synchronization"
