[package]
name = "atomic_pingpong"
version = "0.2.3"
edition = "2021"
authors = ["David Lawrence <dlaw@dlaw.me>"]
license = "MIT"
repository = "https://github.com/dlaw/atomic_pingpong/"
description = "Lightweight no_std ping-pong buffer, using AtomicU8 for synchronization"
